-- models/staging/stg_raw_ecr_enwl_2.sql

with source as (
    select * from {{ source('raw_ecr_enwl_2_source', 'raw_ecr_enwl_2') }}
)

select
    {{ clean_value('"Export MPAN / MSID"') }} as export_mpan,
    {{ clean_value('"Import MPAN / MSID"') }} as import_mpan,
    {{ clean_value('"Customer Name"') }} as customer_name,
    {{ clean_value('"Customer Site"') }} as customer_site,
    {{ clean_value('"Address Line 1"') }} as address_line_1,
    {{ clean_value('"Address Line 2"') }} as address_line_2,
    {{ clean_value('"Town/ City"') }} as town_city,
    {{ clean_value('"County"') }} as county,
    {{ clean_value('"Postcode"') }} as postcode,
    {{ clean_value('"Country"') }} as country,
    "Location (X-coordinate): Eastings (where data is held)" as x_coordinate,
    "Location (y-coordinate): Northings (where data is held)" as y_coordinate,
    {{ clean_value('"Grid Supply Point"') }} as grid_supply_point,
    {{ clean_value('"Bulk Supply Point"') }} as bulk_supply_point,
    {{ clean_value('"Primary"') }} as primary_boundary,
    "Point of Connection (POC) Voltage (kV)" as poc_voltage,
    {{ clean_value('"Licence Area"') }} as licence_area,
    {{ clean_value('"Energy Source 1"') }} as energy_source_1,
    {{ clean_value('"Energy Conversion Technology 1"') }} as energy_conversion_technology_1,
    {{ clean_value('"CHP Cogeneration (Yes/No)"') }} as chp_cogeneration_1,
    "Storage Capacity 1 (MWh)" as storage_capacity_1,
    "Storage Duration 1 (Hours)" as storage_duration_1,
    "Energy Source & Energy Conversion Technology 1 - Registered Cap" as registered_cap_1,
    {{ clean_value('"Energy Source 2"') }} as energy_source_2,
    {{ clean_value('"Energy Conversion Technology 2"') }} as energy_conversion_technology_2,
    {{ clean_value('"CHP Cogeneration 2 (Yes/No)"') }} as chp_cogeneration_2,
    "Storage Capacity 2 (MWh)" as storage_capacity_2,
    "Storage Duration 2 (Hours)" as storage_duration_2,
    "Energy Source & Energy Conversion Technology 2 - Registered Cap" as registered_cap_2,
    {{ clean_value('"Energy Source 3"') }} as energy_source_3,
    {{ clean_value('"Energy Conversion Technology 3"') }} as energy_conversion_technology_3,
    {{ clean_value('"CHP Cogeneration 3 (Yes/No)"') }} as chp_cogeneration_3,
    "Storage Capacity 3 (MWh)" as storage_capacity_3,
    "Storage Duration 3 (Hours)" as storage_duration_3,
    "Energy Source & Energy Conversion Technology 3 - Registered Cap" as registered_cap_3,
    {{ clean_value('"Flexible Connection (Yes/No)"') }} as flexible_connection,
    {{ clean_value('"Connection Status"') }} as connection_status,
    "Already connected Registered Capacity (MW)" as already_connected_registered_capacity,
    "Maximum Export Capacity (MW)" as max_export_capacity_mw,
    "Maximum Export Capacity (MVA)" as max_export_capacity_mva,
    "Maximum Import Capacity (MW)" as max_import_capacity_mw,
    "Maximum Import Capacity (MVA)" as max_import_capacity_mva,
    {{ convert_to_datetime(clean_value('"Date Connected"')) }} as date_connected,
    "Accepted to Connect Registered Capacity (MW)" as accepted_connect_registered_capacity,
    "Change to Maximum Export Capacity (MW)" as change_max_export_capacity_mw,
    "Change to Maximum Export Capacity (MVA)" as change_max_export_capacity_mva,
    "Change to Maximum Import Capacity (MW)" as change_max_import_capacity_mw,
    "Change to Maximum Import Capacity (MVA)" as change_max_import_capacity_mva,
    {{ convert_to_datetime(clean_value('"Date Accepted"')) }} as date_accepted,
    {{ convert_to_datetime(clean_value('"Target Energisation Date"')) }} as target_energisation_date,
    {{ clean_value('"Distribution Service Provider (Y/N)"') }} as distribution_service_provider,
    {{ clean_value('"Transmission Service Provider (Y/N)"') }} as transmission_service_provider,
    {{ clean_value('"Reference"') }} as reference,
    {{ clean_value('"In a Connection Queue (Y/N)"') }} as in_connection_queue,
    {{ clean_value('"Distribution Reinforcement Reference"') }} as distribution_reinforcement_reference,
    {{ clean_value('"Transmission Reinforcement Reference"') }} as transmission_reinforcement_reference,
    {{ convert_to_datetime(clean_value('"Last Updated"')) }} as last_updated,
    {{ clean_value('"geopoint"') }} as geopoint
from source
