-- models/staging/stg_raw_repd_installations.sql

with source as (
    select * from {{ source('raw_repd_installations_source', 'raw_repd_installations') }}
)

select
    {{ clean_value('"Old Ref ID"') }} as old_ref_id,
    {{ clean_value('"Ref ID"') }} as ref_id,
    {{ convert_to_datetime(clean_value('"Record Last Updated (dd/mm/yyyy)"')) }} as last_updated,
    {{ clean_value('"Operator (or Applicant)"') }} as operator_or_applicant,
    {{ clean_value('"Site Name"') }} as customer_site,
    {{ clean_value('"Technology Type"') }} as technology_type,
    {{ clean_value('"Storage Type"') }} as storage_type,
    {{ clean_value('"Storage Co-location REPD Ref ID"') }} as storage_coloc_repd_ref_id,
    "Installed Capacity (MWelec)"::float as registered_cap_1,
    {{ clean_value('"Share Community Scheme"') }} as share_community_scheme,
    {{ clean_value('"CHP Enabled"') }} as chp_enabled,
    {{ clean_value('"CfD Allocation Round"') }} as cfd_allocation_round,
    {{ clean_value('"RO Banding (ROC/MWh)"') }} as ro_banding_roc_mwh,
    {{ clean_value('"FiT Tariff (p/kWh)"') }} as fit_tariff_p_kwh,
    "CfD Capacity (MW)"::float as cfd_capacity_mw,
    {{ clean_value('"Turbine Capacity (MW)"') }} as turbine_capacity_mw,
    {{ clean_value('"No. of Turbines"') }} as no_of_turbines,
    {{ clean_value('"Height of Turbines (m)"') }} as height_of_turbines_m,
    {{ clean_value('"Mounting Type for Solar"') }} as mounting_type_for_solar,
    {{ clean_value('"Development Status"') }} as development_status,
    {{ clean_value('"Development Status (short)"') }} as development_status_short,
    "Are they re-applying (New REPD Ref)" as are_they_re_applying_new_repd_ref,
    "Are they re-applying (Old REPD Ref) " as are_they_re_applying_old_repd_ref,
    {{ clean_value('"Address"') }} as generating_station_address,
    {{ clean_value('"County"') }} as county,
    {{ clean_value('"Region"') }} as region,
    {{ clean_value('"Country"') }} as country,
    {{ clean_value('"Post Code"') }} as post_code,
    "X-coordinate"::float as x_coordinate,
    "Y-coordinate"::float as y_coordinate,
    {{ clean_value('"Planning Authority"') }} as planning_authority,
    {{ clean_value('"Planning Application Reference"') }} as planning_application_reference,
    {{ clean_value('"Appeal Reference"') }} as appeal_reference,
    {{ clean_value('"Secretary of State Reference"') }} as secretary_of_state_reference,
    {{ clean_value('"Type of Secretary of State Intervention"') }} as type_of_secretary_of_state_intervention,
    {{ clean_value('"Judicial Review"') }} as judicial_review,
    {{ clean_value('"Offshore Wind Round"') }} as offshore_wind_round,
    {{ convert_to_datetime(clean_value('"Planning Application Submitted"')) }} as planning_application_submitted,
    {{ convert_to_datetime(clean_value('"Planning Application Withdrawn"')) }} as planning_application_withdrawn,
    {{ convert_to_datetime(clean_value('"Planning Permission Refused"')) }} as planning_permission_refused,
    {{ convert_to_datetime(clean_value('"Appeal Lodged"')) }} as appeal_lodged,
    {{ convert_to_datetime(clean_value('"Appeal Withdrawn"')) }} as appeal_withdrawn,
    {{ convert_to_datetime(clean_value('"Appeal Refused"')) }} as appeal_refused,
    {{ convert_to_datetime(clean_value('"Appeal Granted"')) }} as appeal_granted,
    {{ convert_to_datetime(clean_value('"Planning Permission Granted"')) }} as planning_permission_granted,
    {{ convert_to_datetime(clean_value('"Secretary of State - Intervened"')) }} as secretary_of_state_intervened,
    {{ convert_to_datetime(clean_value('"Secretary of State - Refusal"')) }} as secretary_of_state_refusal,
    {{ convert_to_datetime(clean_value('"Secretary of State - Granted"')) }} as secretary_of_state_granted,
    {{ convert_to_datetime(clean_value('"Planning Permission Expired"')) }} as planning_permission_expired,
    {{ convert_to_datetime(clean_value('"Under Construction"')) }} as under_construction,
    {{ convert_to_datetime(clean_value('"Operational"')) }} as operational,
    {{ clean_value('"Heat Network Ref"') }} as heat_network_ref,
    {{ clean_value('"Solar Site Area (sqm)"') }}::numeric as solar_site_area_sqm,
    -- Create geopoint in EPSG:27700 (British National Grid)
    ST_SetSRID(ST_MakePoint("X-coordinate"::float, "Y-coordinate"::float), 27700) as geopoint
from source