-- models/staging/stg_raw_ecr_ukpn_2.sql

with source as (
    select * from {{ source('raw_ecr_ukpn_2_source', 'raw_ecr_ukpn_2') }}
)

select
    {{ clean_value('"Export MPAN / MSID"') }} as export_mpan,
    {{ clean_value('"Import MPAN / MSID"') }} as import_mpan,
    {{ clean_value('"Customer Name"') }} as customer_name,
    {{ clean_value('"Customer Site"') }} as customer_site,
    {{ clean_value('"Address Line 1"') }} as address_line_1,
    {{ clean_value('"Address Line 2"') }} as address_line_2,
    {{ clean_value('"Town/ City"') }} as town_city,
    {{ clean_value('"County"') }} as county,
    {{ clean_value('"Postcode"') }} as postcode,
    {{ clean_value('"Country"') }} as country,
    {{ clean_value('"Location (X-coordinate):_Eastings (where data is held)"') }} as x_coordinate,
    {{ clean_value('"Location (y-coordinate):_Northings (where data is held)"') }} as y_coordinate,
    {{ clean_value('"Grid Supply Point"') }} as grid_supply_point,
    {{ clean_value('"Bulk Supply Point"') }} as bulk_supply_point,
    {{ clean_value('"Primary"') }} as primary_boundary,
    "Point of Connection (POC)_Voltage (kV)" as poc_voltage,
    {{ clean_value('"Licence Area"') }} as licence_area,
    {{ convert_to_text(clean_value('"Energy Source 1"')) }} as energy_source_1,
    {{ clean_value('"Energy Conversion Technology 1"') }} as energy_conversion_tech_1,
    {{ clean_value('"CHP Cogeneration (Yes/No)"') }} as chp_cogeneration_1,
    {{ clean_value('"Storage Capacity 1 (MWh)"') }} as storage_capacity_1_mwh,
    {{ clean_value('"Storage Duration 1 (Hours)"') }} as storage_duration_1_hours,
    "energy_source_tech1_capacity_mw" as registered_cap_1,
    {{ convert_to_text(clean_value('"Energy Source 2"')) }} as energy_source_2,
    {{ clean_value('"Energy Conversion Technology 2"') }} as energy_conversion_tech_2,
    {{ clean_value('"CHP Cogeneration 2 (Yes/No)"') }} as chp_cogeneration_2,
    {{ clean_value('"Storage Capacity 2 (MWh)"') }} as storage_capacity_2_mwh,
    {{ clean_value('"Storage Duration 2 (Hours)"') }} as storage_duration_2_hours,
    "energy_source_tech2_capacity_mw" as energy_tech_2_cap,
    {{ convert_to_text(clean_value('"Energy Source 3"')) }} as energy_source_3,
    {{ clean_value('"Energy Conversion Technology 3"') }} as energy_conversion_tech_3,
    {{ clean_value('"CHP Cogeneration 3 (Yes/No)"') }} as chp_cogeneration_3,
    {{ clean_value('"Storage Capacity 3 (MWh)"') }} as storage_capacity_3_mwh,
    {{ clean_value('"Storage Duration 3 (Hours)"') }} as storage_duration_3_hours,
    "energy_source_tech3_capacity_mw" as energy_tech_3_cap,
    {{ clean_value('"Flexible Connection (Yes/No)"') }} as flexible_connection,
    {{ clean_value('"Connection Status"') }} as connection_status,
    "Already connected Registered Capacity (MW)" as already_connected_capacity_mw,
    "Already Connected - Maximum Export Capacity (MW)" as max_export_capacity_mw,
    "Already Connected - Maximum Export Capacity (MVA)" as max_export_capacity_mva,
    "Already Connected - Maximum Import Capacity (MW)" as max_import_capacity_mw,
    "Already Connected - Maximum Import Capacity (MVA)" as max_import_capacity_mva,
    {{ convert_to_datetime(clean_value('"Date Connected"')) }} as date_connected,
    "Accepted to Connect Registered Capacity (MW)" as accepted_to_connect_capacity_mw,
    "Accepted to Connect - Change to Maximum Export Capacity (MW)" as change_to_max_export_capacity_mw,
    "Accepted to Connect - Change to Maximum Export Capacity (MVA)" as change_to_max_export_capacity_mva,
    "Accepted to Connect - Change to Maximum Import Capacity (MW)" as change_to_max_import_capacity_mw,
    "Accepted to Connect - Change to Maximum Import Capacity (MVA)" as change_to_max_import_capacity_mva,
    {{ convert_to_datetime(clean_value('"Date Accepted"')) }} as date_accepted,
    {{ convert_to_datetime(clean_value('"Target Energisation Date"')) }} as target_energisation_date,
    {{ clean_value('"Distribution Service Provider (Y/N)"') }} as distribution_service_provider,
    {{ clean_value('"Transmission Service Provider (Y/N)"') }} as transmission_service_provider,
    {{ clean_value('"Reference"') }} as reference,
    {{ clean_value('"In a Connection Queue (Y/N)"') }} as in_connection_queue,
    {{ clean_value('"Distribution Reinforcement Reference"') }} as distribution_reinforcement_reference,
    {{ clean_value('"Transmission Reinforcement Reference"') }} as transmission_reinforcement_reference,
    {{ convert_to_datetime(clean_value('"Last Updated"')) }} as last_updated,
    "Longitude" as longitude,
    "Latitude" as latitude,
    {{ clean_value('"SpatialCoordinates_Customer"') }} as spatial_coordinates_customer,
    {{ clean_value('"SiteFunctionalLocation"') }} as site_functional_location,
    {{ clean_value('"Primary Resource Type_Group"') }} as primary_resource_type_group
from source
